### ISSUE TITLE
search command: IndexError on irrational version # 

### ISSUE THREAD

**Issue by rlbaker** [osupython/pip2#35]
```
$ pip2 search test

Irrational version error found: dev
Irrational version error found: 0
Traceback (most recent call last):
  File "/Users/ryanbaker/dev/capstone/rlbaker/env/bin/pip2", line 9, in <module>
    load_entry_point('pip2==0.0.1', 'console_scripts', 'pip2')()
  File "/Users/ryanbaker/dev/capstone/rlbaker/pip2/pip2/__init__.py", line 9, in main
    args.func(args)
  File "/Users/ryanbaker/dev/capstone/rlbaker/pip2/pip2/cli_wrapper.py", line 35, in search
    results = pip2.commands.search.search(args.package)
  File "/Users/ryanbaker/dev/capstone/rlbaker/pip2/pip2/commands/search.py", line 38, in search
    release = project.releases[0]
IndexError: list index out of range
```

**Comment by michaeta** [comment]
I'm working on it. Its already in a try except clause and I made a mention of it in the comments. How do you think we should handle it? Just skip over it or mention it to the user?

**Comment by rlbaker** [comment]
Maybe notify the user that it was unable to find a properly versioned package or something? Good question for the mailing list.
